# Docker compose file for building docker images and running locally

version: '3.8'

services:
  book_catalog:
    build:
     context: ./book_catalog
     dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://example_3_d04b_user:PB1XVjhThTqq5RHshJ6pX8R7huulaPfe@dpg-crmi51a3esus73ftl7jg-a.oregon-postgres.render.com/example_3_d04b


  inventory_management:
    build:
     context: ./inventory_management
     dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
     - DATABASE_URL=postgresql://example_3_d04b_user:PB1XVjhThTqq5RHshJ6pX8R7huulaPfe@dpg-crmi51a3esus73ftl7jg-a.oregon-postgres.render.com/example_3_d04b

